export const queries ={ 
  getAllAlumnos:'SELECT * FROM ALUMNO;',
  addNewAlumno: 'INSERT INTO ALUMNO (CI_ALUMNO, NOMBRE_ALUMNO, APELLIDO_ALUMNO, CELULAR_ALUMNO) VALUES (@CI_ALUMNO, @NOMBRE_ALUMNO, @APELLIDO_ALUMNO, @CELULAR_ALUMNO)',
  getAlumnoById:'SELECT * FROM ALUMNO WHERE ID_ALUMNO = @Id',
  deleteAlumnoById:'DELETE FROM ALUMNO WHERE ID_ALUMNO = @Id',
  updateAlumnoById:'UPDATE ALUMNO SET CI_ALUMNO = @CI_ALUMNO, NOMBRE_ALUMNO = @NOMBRE_ALUMNO, APELLIDO_ALUMNO = @APELLIDO_ALUMNO, CELULAR_ALUMNO =  @CELULAR_ALUMNO WHERE ID_ALUMNO = @Id',
}