export const queries = {
  getAllAlumnos: 'SELECT * FROM ALUMNO;',
  addNewAlumno: 'INSERT INTO ALUMNO (CI_ALUMNO, NOMBRE_ALUMNO, APELLIDO_ALUMNO, CELULAR_ALUMNO) VALUES (@CI_ALUMNO, @NOMBRE_ALUMNO, @APELLIDO_ALUMNO, @CELULAR_ALUMNO)',
  getAlumnoById: 'SELECT * FROM ALUMNO WHERE ID_ALUMNO = @Id',
  deleteAlumnoById: 'DELETE FROM ALUMNO WHERE ID_ALUMNO = @Id',
  updateAlumnoById: 'UPDATE ALUMNO SET CI_ALUMNO = @CI_ALUMNO, NOMBRE_ALUMNO = @NOMBRE_ALUMNO, APELLIDO_ALUMNO = @APELLIDO_ALUMNO, CELULAR_ALUMNO =  @CELULAR_ALUMNO WHERE ID_ALUMNO = @Id',
  /*----------------------------------------------------------------------------------------*/
  getAllProfesores: 'SELECT * FROM PROFESOR;',
  addNewProfesor: 'INSERT INTO PROFESOR (CI_PROFESOR, NOMBRE_PROFESOR, APELLIDO_PROFESOR, CELULAR_PROFESOR, PROFESION_PROFESOR) VALUES (@CI_PROFESOR, @NOMBRE_PROFESOR, @APELLIDO_PROFESOR, @CELULAR_PROFESOR, @PROFESION_PROFESOR)',
  getProfesorById: 'SELECT * FROM PROFESOR WHERE ID_PROFESOR = @Id',
  deleteProfesorById: 'DELETE FROM PROFESOR WHERE ID_PROFESOR = @Id',
  updateProfesorById: 'UPDATE PROFESOR SET CI_PROFESOR = @CI_PROFESOR, NOMBRE_PROFESOR = @NOMBRE_PROFESOR, APELLIDO_PROFESOR = @APELLIDO_PROFESOR, CELULAR_PROFESOR =  @CELULAR_PROFESOR, PROFESION_PROFESOR = @PROFESION_PROFESOR WHERE ID_PROFESOR = @Id',
  /*----------------------------------------------------------------------------------------*/
  getAllMaterias: 'SELECT * FROM MATERIA;',
  addNewMateria: 'INSERT INTO MATERIA (ID_PROFESOR, NOMBRE_MATERIA) VALUES (@ID_PROFESOR, @NOMBRE_MATERIA)',
  getMateriaById: 'SELECT * FROM MATERIA WHERE ID_MATERIA = @Id',
  deleteMateriaById: 'DELETE FROM MATERIA WHERE ID_MATERIA = @Id',
  updateMateriaById: 'UPDATE MATERIA SET ID_PROFESOR = @ID_PROFESOR, NOMBRE_MATERIA = @NOMBRE_MATERIA WHERE ID_MATERIA = @Id',
  /*----------------------------------------------------------------------------------------*/
  getAllAsistencias: 'SELECT * FROM ASISTENCIA;',
  addNewAsistencia: 'INSERT INTO ASISTENCIA (ID_ALUMNO, ID_MATERIA, FECHA_ASISTENCIA, ASISTENCIA) VALUES (@ID_ALUMNO, @ID_MATERIA, @FECHA_ASISTENCIA, @ASISTENCIA)',
  getAsistenciaById: 'SELECT * FROM ASISTENCIA WHERE ID_ASISTENCIA = @Id',
  deleteAsistenciaById: 'DELETE FROM ASISTENCIA WHERE ID_ASISTENCIA = @Id',
  updateAsistenciaById: 'UPDATE ASISTENCIA SET ID_ALUMNO = @ID_ALUMNO, ID_MATERIA = @ID_MATERIA, FECHA_ASISTENCIA = @FECHA_ASISTENCIA, ASISTENCIA = @ASISTENCIA WHERE ID_ASISTENCIA = @Id',
  /*----------------------------------------------------------------------------------------*/
  /* Busquedas especialidas */
  /* Alumno */
  /*Ingresar un alumno e indique cuantas faltas tiene*/
  getFaltasPorAlumno: "select NOMBRE_MATERIA,count( NOMBRE_MATERIA) as 'INASISTENCIA' FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA WHERE ASISTENCIA =0 AND NOMBRE_ALUMNO = @NOMBRE_ALUMNO group by NOMBRE_MATERIA",


  /*obtener los estudiantes que faltaron en un rango de Fechas
  ejemplo: que estudiantes faltaron  entre el 2022-06-01 hasta 2022-06-30
  */

  getFaltasPorAlumnoFecha: "select NOMBRE_ALUMNO,FECHA_ASISTENCIA, NOMBRE_MATERIA FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA WHERE ASISTENCIA =0 AND FECHA_ASISTENCIA BETWEEN '2022-06-01' AND'2022-06-30';",


  /*Listado de Estudiantes con un numero determinado de faltas*/
  getAlumnoFaltaNumero: "select NOMBRE_ALUMNO FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA WHERE ASISTENCIA =0 group by NOMBRE_ALUMNO HAVING COUNT(ASISTENCIA) >=@falta",

  /* Profesor */

  /*Los profesores y las materias*/

  getProfesorMateria: 'select NOMBRE_PROFESOR, NOMBRE_MATERIA FROM dbo.PROFESOR INNER JOIN dbo.MATERIA ON dbo.PROFESOR.ID_PROFESOR = dbo.MATERIA.ID_PROFESOR;',

  /* Numero de Estudiantes por profesor*/

  getProfesorNumeroEstudiantes: "select NOMBRE_PROFESOR,NOMBRE_MATERIA, COUNT(NOMBRE_ALUMNO) AS 'NUMERO ALUMNOS' FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA INNER JOIN dbo.PROFESOR ON dbo.MATERIA.ID_PROFESOR = dbo.PROFESOR.ID_PROFESOR group by NOMBRE_PROFESOR,NOMBRE_MATERIA ORDER BY NOMBRE_PROFESOR ;",


  /*INGRESAR UN PROFESOR Y MUESTRE QUE MATERIAS IMPARTE*/

  getMateriaPorNombreProfesor: "select NOMBRE_MATERIA FROM dbo.PROFESOR INNER JOIN dbo.MATERIA ON dbo.PROFESOR.ID_PROFESOR = dbo.MATERIA.ID_PROFESOR WHERE NOMBRE_PROFESOR = @NOMBRE_PROFESOR AND APELLIDO_PROFESOR = @APELLIDO_PROFESOR;",

  /* Materia*/

  /*Las materias con mas faltas*/
  getMateriaMasFaltas: "select NOMBRE_MATERIA,COUNT(NOMBRE_MATERIA) AS 'TOTAL FALTAS' FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA WHERE ASISTENCIA =0 group by NOMBRE_MATERIA ORDER BY COUNT(NOMBRE_MATERIA) DESC;",

  /*listado de estudiantes inscritos en una materia*/

  getMateriaListado: "select DISTINCT NOMBRE_MATERIA,NOMBRE_ALUMNO FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA WHERE NOMBRE_MATERIA = @NOMBRE_MATERIA;",


  

/*Las materias con mas asistencias*/
  getMateriaMasAsiatencias:"select NOMBRE_MATERIA,COUNT(NOMBRE_MATERIA) AS 'TOTAL FALTAS' FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA WHERE ASISTENCIA =1  group by NOMBRE_MATERIA ORDER BY COUNT(NOMBRE_MATERIA) DESC;",

  /* Asistencia */
  /*Asistencias por fecha*/
  getAsistenciaPorFecha: 'select NOMBRE_MATERIA, FECHA_ASISTENCIA,NOMBRE_ALUMNO FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA ORDER BY FECHA_ASISTENCIA DESC;',

  /*Asistencia po Materia*/

  getAsistenciaPorMateria: 'select NOMBRE_MATERIA, FECHA_ASISTENCIA,NOMBRE_ALUMNO FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA ORDER BY NOMBRE_MATERIA DESC;',

  /*inasistencia por alumno y materia*/

  getInasistenciaAlumnoMateria: "select NOMBRE_ALUMNO,NOMBRE_MATERIA,count( NOMBRE_MATERIA) as 'INASISTENCIA' FROM dbo.ALUMNO INNER JOIN dbo.ASISTENCIA ON dbo.ALUMNO.ID_ALUMNO = dbo.ASISTENCIA.ID_ALUMNO INNER JOIN dbo.MATERIA ON dbo.ASISTENCIA.ID_MATERIA = dbo.MATERIA.ID_MATERIA  WHERE ASISTENCIA = 0 group by NOMBRE_ALUMNO,NOMBRE_MATERIA",



}